name: VAULTIS Runner Ops Loop

on:
  schedule:
    - cron: '0 */2 * * *' # Every 2 hours
  push:
    paths:
      - 'Codex16/**'
  workflow_dispatch: # Allow manual triggering

jobs:
  run-ops-loop:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper git operations

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml schedule requests

      - name: Create required directories
        run: |
          mkdir -p Logs SITREPs Scripts

      - name: Run Drift Monitor
        run: python Scripts/vector_monitor.py
        continue-on-error: true # Continue even if this step fails

      - name: Generate SITREP
        run: python Scripts/generate_sitrep.py
        continue-on-error: true # Continue even if this step fails

      - name: Commit and push updates
        run: |
          git config user.name "VAULTIS Runner"
          git config user.email "runner@nightwalker.ai"
          git pull origin main --rebase --autostash
          git add Logs/ SITREPs/
          git diff --staged --quiet || git commit -m "[AUTO] VAULTIS Drift Monitor and SITREP Update"
          git push origin main
